name: Merge and PR build test
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: .NET environment setup
        uses: ./.github/actions/setup/dotnet

      - name: Build portable
        uses: ./.github/actions/build/default
        with:
          configuration: Portable (Release)
          assembly: Innovation Uniform Editor

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Uniform-Editor-BUGTEST-PR"
          path: "./Innovation Uniform Editor/bin/Release/**"
